services:
  - type: web
    name: gharik-wallet
    runtime: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: PORT
        value: 10000
    region: oregon
    plan: free
